function meas = meas21()

labels = {'Fp2';  'F8';   'T4';   'T6';   '02';  ...
         'F4';   'C4';   'P4';   'Fz';  'Cz';  ...
         'Pz';   'Fp1';   'F7';   'T3';   'T5';  ...
	 'O1';   'F3';   'C3';   'P3';'T2'; 'T1'};

mont = (1:21)';

nofel = size(labels,1);
      
mont = [ 1  ;...
        2   ;...
        3   ;...
	    4  ;...
	    5  ;...
        6  ;...
        7  ;...
        8  ;...
        9   ;...
        10  ;... 
        11  ;...
        12  ;...
        13  ;...
        14  ;...
        15  ;...
        16  ;...
        17 ;...
        18 ;...
        19 ;...
        20;...
        21];

      
groupnames = {'Scalp Electrodes'};

% 

meas.el.lbl         = labels;
meas.el.cls         = ones(nofel,1);
meas.el.grp         = ones(nofel,1);
meas.el.grplbl      = groupnames;
meas.el.pos.std     = elpos19osg;
meas.el.pos.sph     = zeros(nofel,2);
meas.el.pos.realmr  = zeros(nofel,2);
meas.el.pos.realana = zeros(nofel,2);


meas.mont           = mont;


